version: '3'
services:
  web:
    build: .
    command: mix phx.server
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
    depends_on:
      - postgres 
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: phx_shop_api_db_user
      POSTGRES_PASSWORD: phx_shop_super_good_secret_password
      POSTGRES_DB: phx_shop_api_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
